# Generated by Django 5.2 on 2025-05-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='linktoplaylist',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
